apiVersion: v1
kind: Pod
metadata:
  name: hornet
  labels:
    app: hornet
spec:

  initContainers:

  - name: take-data-dir-ownership
    image: alpine:3
    command:
    - chown
    - -R
    - 65532:65532
    - /app/mainnetdb
    - /app/snapshots
    - /app/p2pstore
    volumeMounts:
    - name: mainnetdb
      mountPath: /app/mainnetdb
    - name: snapshots
      mountPath: /app/snapshots/mainnet
    - name: p2pstore
      mountPath: /app/p2pstore

  - name: configure-coordinator-and-autopeering
    image: stedolan/jq
    command: ["/init-scripts/hornet-config.sh"]
    securityContext:
      allowPrivilegeEscalation: false    
    volumeMounts:
    - name: init-configuration
      mountPath: /init-scripts
    - name: configuration
      mountPath: /config
    - name: init-tmp
      mountPath: /config-out
    envFrom:
    - secretRef:
        name: hornet-dashboard-secret


  containers:
  - name: hornet
    image: gohornet/hornet:1.0.5
    args: 
    - "--config"
    - "/config-out/config.json"
    - "--peering"
    - "/config/peering.json"
    - "--profiles"
    - "/config/profiles.json"
    resources:
      requests:
        memory: "100Mi"
        cpu: "250m"
    #  limits:
    #    memory: "8000Mi"
    #    cpu: "4000m"
    securityContext:
      allowPrivilegeEscalation: false    
    readinessProbe:
      httpGet:
        path: /health
        port: 14265
    ports:
    - name: gossip
      protocol: TCP
      containerPort: 15600
    - name: autopeering
      protocol: UDP
      containerPort: 14626
    - name: rest
      protocol: TCP
      containerPort: 14265
    - name: dashboard
      protocol: TCP
      containerPort: 8081
    - name: mqtt
      protocol: TCP
      containerPort: 1883
    volumeMounts:
    - name: init-tmp
      mountPath: /config-out
    - name: configuration
      mountPath: /config
    - name: mainnetdb
      mountPath: /app/mainnetdb
    - name: snapshots
      mountPath: /app/snapshots/mainnet
    - name: p2pstore
      mountPath: /app/p2pstore

  volumes:
  - name: init-tmp
    emptyDir: {}
  - name: p2pstore
    persistentVolumeClaim:
      claimName: hornet-p2pstore-pvc
  - name: mainnetdb
    persistentVolumeClaim:
      claimName: hornet-mainnetdb-pvc
  - name: snapshots
    persistentVolumeClaim:
      claimName: hornet-snapshot-pvc
  - name: init-configuration
    configMap:
      name: init-hornet-config
      defaultMode: 0777
  - name: configuration 
    configMap:
      name: hornet-config
      items:
      - key: config-template.json
        path: config-template.json
      - key: profiles.json
        path: profiles.json
      - key: peering.json
        path: peering.json
