# Dashboard credentials for the word "admin" was created with
#
# $ docker run  -it gohornet/hornet:latest /app/hornet tool pwd-hash
# $ Enter a password: 
# $ Re-enter your password: 
# $ Success!
# $ Your hash: f7ff338e38bc7f02524c6175517e9cbeca7310293b5f245ec1022ad361615f40
# $ Your salt: 8e44e479cf9cf0d3d1a316df34f8466c3188cfccb39caa68ad48966697955147
# $ echo -n "f7ff338e38bc7f02524c6175517e9cbeca7310293b5f245ec1022ad361615f40" | base64
# $ echo -n "8e44e479cf9cf0d3d1a316df34f8466c3188cfccb39caa68ad48966697955147" | base64
#
apiVersion: v1
kind: Secret
metadata:
  name: hornet-dashboard-secret
type: Opaque
data:
  PASSWORD_HASH: ZjdmZjMzOGUzOGJjN2YwMjUyNGM2MTc1NTE3ZTljYmVjYTczMTAyOTNiNWYyNDVlYzEwMjJhZDM2MTYxNWY0MA==
  PASSWORD_SALT: OGU0NGU0NzljZjljZjBkM2QxYTMxNmRmMzRmODQ2NmMzMTg4Y2ZjY2IzOWNhYTY4YWQ0ODk2NjY5Nzk1NTE0Nw==
