apiVersion: v1
kind: Service
metadata:
  name: hornet-udp
spec:
  type: NodePort
  ports:
  - name: autopeering
    port: 30100
    nodePort: 30100
    protocol: UDP
    targetPort: autopeering
  selector:
    app: hornet
---
apiVersion: v1
kind: Service
metadata:
  name: hornet-tcp
spec:
  type: ClusterIP
  ports:
  - name: gossip
    port: 15600
    protocol: TCP
    targetPort: gossip
  - name: rest
    port: 14265
    protocol: TCP
    targetPort: 14265
  - name: dashboard
    port: 8081
    protocol: TCP
    targetPort: dashboard
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
  selector:
    app: hornet
