version: "3"

networks:
  tangle:
    external:
      name: private-tangle

services:
  coo:
    hostname: coo
    # network_mode: host
    networks:
      - tangle
    image: gohornet/hornet:1.2.0
    restart: unless-stopped
    container_name: coo
    stop_grace_period: 5m
    environment:
      - COO_PRV_KEYS
    expose:
      - 15600
    volumes:
      - ./config/config-coo.json:/app/config.json:ro
      - ./config/profiles.json:/app/profiles.json:ro
      - ./config/peering-coo.json:/app/peering.json:ro
      - ./db/private-tangle/coo.db:/app/db
      - ./p2pstore/coo:/app/p2pstore
      - ./db/private-tangle:/app/coo-state
      - ./snapshots:/app/snapshots
    cap_drop:
      - ALL
  
  node:
    hostname: node1
    # network_mode: host
    networks:
      - tangle
    image: gohornet/hornet:1.2.0
    restart: unless-stopped
    container_name: node1
    stop_grace_period: 5m
    expose:
      - 14265
      - 8081
      - 1883
      - 15600
      - "14626/udp"
    ports:
      - "0.0.0.0:14265:14265"
      - "0.0.0.0:8081:8081"
      - "0.0.0.0:15600:15600"
    volumes:
      - ./config/config-node.json:/app/config.json:ro
      - ./config/profiles.json:/app/profiles.json
      - ./config/peering-node.json:/app/peering.json
      - ./db/private-tangle/node1.db:/app/db
      - ./p2pstore/node1:/app/p2pstore
      - ./snapshots:/app/snapshots
    cap_drop:
        - ALL
  
  spammer:
    hostname: spammer
    # network_mode: host
    networks:
      - tangle
    image: gohornet/hornet:1.2.0
    restart: unless-stopped
    container_name: spammer
    stop_grace_period: 5m
    expose:
      - 15600
      - "14626/udp"
    volumes:
      - ./config/config-spammer.json:/app/config.json:ro
      - ./config/profiles.json:/app/profiles.json
      - ./config/peering-spammer.json:/app/peering.json
      - ./db/private-tangle/spammer.db:/app/db
      - ./p2pstore/spammer:/app/p2pstore
      - ./snapshots:/app/snapshots
    cap_drop:
        - ALL

  node-autopeering:
    hostname: node-autopeering
    # network_mode: host
    networks:
      - tangle
    image: gohornet/hornet:1.2.0
    restart: unless-stopped
    container_name: node-autopeering
    stop_grace_period: 5m
    expose:
      - "14626/udp"
    ports:
      - "0.0.0.0:14626:14626/udp"
    volumes:
      - ./config/config-autopeering.json:/app/config.json:ro
      - ./config/profiles.json:/app/profiles.json
      - ./db/private-tangle/node-autopeering.db:/app/db
      - ./p2pstore/node-autopeering:/app/p2pstore
    cap_drop:
        - ALL
