apiVersion: v1
kind: Service
metadata:
  name: hornet-rest
  labels:
    app: hornet-api
    source: one-click-tangle
spec:
  type: NodePort
  ports:
  - name: rest
    port: 14265
    protocol: TCP
    targetPort: 14265
  selector:
    app: hornet
