version: "3"

networks:
  tangle:
    external:
      name: private-tangle

services:
  explorer-api:
    hostname: explorer-api
    networks:
      - tangle
    build:
       context: ./explorer-src/api
       dockerfile: Dockerfile
    image: iotaledger/explorer-api
    restart: unless-stopped
    container_name: explorer-api
    expose:
      - 4000
    ports:
      - "0.0.0.0:4000:4000"
    volumes:
      - ./application-data:/app/data/.local-storage

  explorer-webapp:
    hostname: explorer-webapp
    networks:
      - tangle
    build:
      context: ./explorer-src/client
      dockerfile: Dockerfile
    image: iotaledger/explorer-webapp
    restart: unless-stopped
    container_name: explorer-webapp
    depends_on:
      - explorer-api
    expose: 
      - 80
    ports:
      - "0.0.0.0:8082:80"
