version: "3"

networks:
  tangle:
    external:
      name: private-tangle

services:
  
  node:
    hostname: node
    # network_mode: host
    networks:
      - tangle
    image: gohornet/hornet:latest
    restart: unless-stopped
    container_name: node
    expose:
      - 14265
      - 8081
      - 15600
      - "14626/udp"
    volumes:
      - ./config/config.json:/app/config.json:ro
      - ./config/profiles.json:/app/profiles.json
      - ./config/peering.json:/app/peering.json
      - ./db:/app/db
      - ./p2pstore:/app/p2pstore
      - ./snapshots:/app/snapshots
    cap_drop:
        - ALL
  